import { scrollLengthFromBeats } from "../story-timing";
import { multiServiceScenes } from "./multi-service";
import type { ChapterConfig, SceneConfig } from "./types";

const sceneBeatCounts = {
  scene1: 4,
  scene2: 4,
  scene3: 6,
  scene4: 4,
  scene5: 3,
  scene6: 8,
  scene7: 4,
  scene8: 4,
} as const;

const sceneScrollLengths = {
  scene1: scrollLengthFromBeats(sceneBeatCounts.scene1),
  scene2: scrollLengthFromBeats(sceneBeatCounts.scene2),
  scene3: scrollLengthFromBeats(sceneBeatCounts.scene3),
  scene4: scrollLengthFromBeats(sceneBeatCounts.scene4),
  scene5: scrollLengthFromBeats(sceneBeatCounts.scene5),
  scene6: scrollLengthFromBeats(sceneBeatCounts.scene6, 2),
  scene7: scrollLengthFromBeats(sceneBeatCounts.scene7),
  scene8: scrollLengthFromBeats(sceneBeatCounts.scene8),
} as const;

export const airportNapScenes: SceneConfig[] = [
    {
      id: "scene-1",
      name: "Airport Choice",
      goal: "Introduce Pico, the airport setting, and the two nap pods.",
      stageId: "opening-world",
      backgroundMode: "airport",
      scrollLength: sceneScrollLengths.scene1,
      sticky: true,
      asset: "/chapter1/c1-storyboard-1-start.svg",
      assetAlt: "Traditional and Fiber nap pods side by side in the airport.",
      copy: {
        eyebrow: "Scene 1",
        headline: "After a long flight, all I need is a quick nap.",
        body: "They look exactly the same.",
        caption: "...so what’s the difference?",
      },
    },
    {
      id: "scene-2",
      name: "Traditional Pricing",
      goal: "Show why fixed-duration pricing is awkward for uncertain needs.",
      stageId: "opening-world",
      backgroundMode: "white",
      scrollLength: sceneScrollLengths.scene2,
      sticky: true,
      asset: "/chapter1/c1-storyboard-2-start.svg",
      assetAlt: "Traditional nap pod pricing board.",
      copy: {
        eyebrow: "Scene 2",
        headline: "I have to choose a package before I know how long I’ll sleep.",
        body: "How does Fiber work?",
        caption: "",
      },
    },
    {
      id: "scene-3",
      name: "Fiber Pricing",
      goal: "Show that Fiber supports true pay-as-you-go usage.",
      stageId: "opening-world",
      backgroundMode: "white",
      scrollLength: sceneScrollLengths.scene3,
      sticky: true,
      asset: "/chapter1/c1-storyboard-3.svg",
      assetAlt: "Fiber nap pod with pay-as-you-use pricing.",
      copy: {
        eyebrow: "Scene 3",
        headline: "How does Fiber charge?",
        body: "Oh, this is way better!",
        caption: "No guessing upfront. Fiber charges only for the seconds I actually use.",
      },
    },
    {
      id: "scene-4",
      name: "Tap To Start",
      goal: "Introduce the deposit and start action.",
      stageId: "transition-world",
      backgroundMode: "white",
      scrollLength: sceneScrollLengths.scene4,
      sticky: true,
      asset: "/storyboards/scene-4.png",
      assetAlt: "Pico tapping the Fiber start screen and confirming on phone.",
      copy: {
        eyebrow: "Scene 4",
        headline: "Pico taps to start and sets aside a deposit.",
        body: "The session begins with a single tap. Fiber locks a deposit in the background so the pod can charge smoothly while Pico sleeps.",
        caption: "Unused balance will return automatically at the end.",
      },
    },
    {
      id: "scene-5",
      name: "Channel Opening",
      goal: "Explain that Fiber opens the payment channel behind the scenes.",
      stageId: "technical-world",
      backgroundMode: "warm",
      scrollLength: sceneScrollLengths.scene5,
      sticky: true,
      asset: "/storyboards/scene-5-start.png",
      assetAlt: "Payment channel moving from opening to active.",
      copy: {
        eyebrow: "Scene 5",
        headline: "Behind the scenes, Fiber opens a payment channel.",
        body: "The deposit is funded once on Layer 1, then the payment channel becomes active. That setup lets the actual usage updates happen off-chain.",
        caption: "The user experience stays simple while the financial plumbing comes online.",
      },
    },
    {
      id: "scene-6",
      name: "Micropayments",
      goal: "Show off-chain micropayments during usage.",
      stageId: "technical-world",
      backgroundMode: "sleep",
      scrollLength: sceneScrollLengths.scene6,
      sticky: true,
      asset: "/storyboards/scene-6.png",
      assetAlt: "Micropayments happening off-chain while Pico sleeps.",
      copy: {
        eyebrow: "Scene 6",
        headline: "While Pico sleeps, tiny payments update off-chain in Layer 2.",
        body: "Tiny updates happen inside the channel, so Layer 1 does not need a transaction every second.",
        caption: "This is where pay-as-you-go becomes practical.",
      },
    },
    {
      id: "scene-7",
      name: "Final Settlement",
      goal: "Show the channel closing and the final Layer 1 settlement.",
      stageId: "settlement-world",
      backgroundMode: "settlement",
      scrollLength: sceneScrollLengths.scene7,
      sticky: true,
      asset: "/storyboards/scene-7-start.png",
      assetAlt: "Payment channel closing and final Layer 1 settlement.",
      copy: {
        eyebrow: "Scene 7",
        headline: "When the session ends, only the final result settles on Layer 1.",
        body: "Once Pico is done, the payment channel closes. The final split between paid usage and returned balance is then reflected on Layer 1.",
        caption: "The end result: Pico only pays for what was actually used.",
      },
    },
    {
      id: "scene-8",
      name: "Exact Billing",
      goal: "Show that the final charge only reflects actual time used.",
      stageId: "technical-world",
      backgroundMode: "reveal",
      scrollLength: sceneScrollLengths.scene8,
      sticky: true,
      asset: "/chapter1/c1-storyboard-8-left-start.svg",
      assetAlt: "Fiber session ended summary on Pico's phone.",
      copy: {
        eyebrow: "Scene 8",
        headline: "Pico wakes up and pays only for the exact usage.",
        body: "The session summary shows the precise amount consumed during the nap. Everything left over from the deposit comes back.",
        caption: "No extra package padding. No need to estimate in advance.",
      },
    }
];

export const airportNapChapter: ChapterConfig = {
  slug: "airport-nap",
  title: "Airport Nap",
  summary: "Pico compares a traditional nap pod with a Fiber-powered one and discovers what pay-as-you-go really means.",
  estimatedDuration: "2 min",
  status: "available",
  coverAsset: "/storyboards/scene-1.png",
  coverAlt: "Pico comparing traditional and Fiber nap pods.",
  scenes: [...airportNapScenes, ...multiServiceScenes],
};
